### PR TITLE
Redis::add does not exist

### PR DESCRIPTION
**Pull request by cankaratoprak**
ARedisConnection client, i.e. Redis class does not have a method named add. Instead setnx and expire should be used.

### CODE REVIEW

**Comment by phpnode** [comment]
Thanks for pointing this out, it should actually be set() not setnx(), I've fixed this myself in the last commit

**Comment by phpnode** [comment]
ah, you're right, it should be setnx, fixed

**Comment by cankaratoprak** [comment]
Thanks for the fix.

I think setValue and addValue should return a boolean value indicating the result of the operation.

I have another suggestion. I am not 100% sure, but I think ARedisSet::contains() function may use Redis::sIsMember() for performance. It currently inherits the parent function which gets all the data and uses in_array. sIsMember directly returns true or false without getting all the data.

Best regards and thank you for this great extension.

**Comment by phpnode** [comment]
Thanks for your suggestions, fixed in the latest commits.

**Pull request closed without merging**
